[build]
  # Build command for the dashboard
  command = "cd dashboard && npm install && npm run build"
  # Directory to publish
  publish = "dashboard/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Build environment
  NODE_ENV = "production"

# SPA routing configuration for dashboard
[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API proxy configuration (connects to your existing backend)
[[redirects]]
  from = "/api/*"
  to = "https://api.lanonasis.com/api/:splat"
  status = 200
  force = true

# SSE endpoint proxy
[[redirects]]
  from = "/sse"
  to = "https://api.lanonasis.com/sse"
  status = 200
  force = true

# MCP SSE endpoint proxy
[[redirects]]
  from = "/mcp/sse"
  to = "https://api.lanonasis.com/mcp/sse"
  status = 200
  force = true
