apiVersion: v1
kind: ConfigMap
metadata:
  name: memory-service-config
  namespace: memory-service
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  API_VERSION: "v1"
  API_PREFIX: "/api"
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  JWT_EXPIRES_IN: "24h"