apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-service
  namespace: memory-service
  labels:
    app: memory-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-service
  template:
    metadata:
      labels:
        app: memory-service
        version: v1
    spec:
      containers:
      - name: memory-service
        image: seyederick/memory-service:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: memory-service-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: memory-service-config
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: memory-service-config
              key: HOST
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: memory-service-config
              key: LOG_LEVEL
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: memory-service-secrets
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: memory-service-secrets
              key: SUPABASE_KEY
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: memory-service-secrets
              key: SUPABASE_SERVICE_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: memory-service-secrets
              key: JWT_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: memory-service-secrets
              key: OPENAI_API_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: memory-service-secrets
              key: REDIS_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health/live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      securityContext:
        fsGroup: 1001