apiVersion: v1
kind: Secret
metadata:
  name: memory-service-secrets
  namespace: memory-service
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  SUPABASE_URL: <base64-encoded-supabase-url>
  SUPABASE_KEY: <base64-encoded-supabase-key>
  SUPABASE_SERVICE_KEY: <base64-encoded-supabase-service-key>
  JWT_SECRET: <base64-encoded-jwt-secret>
  OPENAI_API_KEY: <base64-encoded-openai-key>
  REDIS_URL: <base64-encoded-redis-url>

---
# Example of how to create secrets:
# kubectl create secret generic memory-service-secrets \
#   --from-literal=SUPABASE_URL=your_supabase_url \
#   --from-literal=SUPABASE_KEY=your_supabase_key \
#   --from-literal=SUPABASE_SERVICE_KEY=your_service_key \
#   --from-literal=JWT_SECRET=your_jwt_secret \
#   --from-literal=OPENAI_API_KEY=your_openai_key \
#   --from-literal=REDIS_URL=redis://redis-service:6379 \
#   --namespace=memory-service